export const equipmentList = [
  { name: "Forklift", slug: "forklift", description: "Industrial forklifts for material handling and warehouse operations." },
  { name: "Wheel Loader", slug: "wheel-loader", description: "Heavy-duty wheel loaders for construction and loading operations." },
  { name: "JCB Backhoe Loader", slug: "backhoe-loader", description: "Versatile JCB Backhoe 3CX for excavation and loading tasks." },
  { name: "Boom Loader", slug: "boom-loader", description: "Telehandlers and boomloaders for reaching high and extended areas." },
  { name: "Excavator", slug: "excavator", description: "Compact mini excavators for tight spaces and small projects." },
  { name: "Crane", slug: "crane", description: "Mobile and tower cranes for heavy lifting operations." },
  { name: "Manlift", slug: "manlift", description: "Aerial work platforms for elevated work access." },
  { name: "Scissor Lift", slug: "scissor-lift", description: "Scissor lifts for vertical elevation in construction and maintenance." },
  { name: "Roller", slug: "roller", description: "Road rollers and compactors for road construction." },
  { name: "Recovery Truck", slug: "recovery-truck", description: "10-ton recovery trucks for vehicle recovery and towing." },
  { name: "Generator", slug: "generator", description: "Power generators for construction sites and events." },
  { name: "Compressor", slug: "compressor", description: "Air compressors for pneumatic tools and industrial use." },
  { name: "Skid Steer Loader", slug: "skid-steer", description: "Bobcat skid steer loaders for versatile construction tasks." },
  { name: "Passenger Bus", slug: "passenger-bus", description: "Passenger buses for staff and workforce transportation." },
];

export const servicesList = [
  { name: "Leasing of Machineries & Equipments", slug: "leasing-machineries-equipments", description: "Flexible leasing options for all types of heavy machinery and construction equipment." },
  { name: "Supply of Trained Operators", slug: "supply-trained-operators", description: "Skilled and certified operators for safe and efficient equipment operation." },
  { name: "Equipment Repair & Maintenance Services", slug: "equipment-repair-maintenance", description: "Comprehensive repair and maintenance services to keep your equipment running." },
  { name: "Quality-Assured Industrial Equipment", slug: "quality-assured-equipment", description: "High-quality, regularly inspected industrial equipment for all projects." },
  { name: "Welding & Cutting Equipment", slug: "welding-cutting-equipment", description: "Professional welding and cutting equipment for industrial applications." },
  { name: "Heavy Duty Construction Machinery", slug: "heavy-duty-construction", description: "Robust heavy-duty machinery for large-scale construction projects." },
  { name: "Scaffolding", slug: "scaffolding", description: "Safe and reliable scaffolding solutions for construction and maintenance." },
  { name: "Logistic & Operator Support", slug: "logistic-operator-support", description: "End-to-end logistics and on-site operator support services." },
  { name: "Workshop & Maintenance", slug: "workshop-maintenance", description: "Fully equipped workshop for equipment servicing and repairs." },
];

export const blogPosts = [
  {
    id: 1,
    title: "Top 10 Heavy Equipment for Construction Projects",
    slug: "top-10-heavy-equipment-construction",
    excerpt: "Discover the essential heavy equipment needed for modern construction projects in the UAE.",
    date: "2024-12-15",
    image: "/placeholder.svg",
  },
  {
    id: 2,
    title: "How to Choose the Right Excavator for Your Project",
    slug: "choose-right-excavator",
    excerpt: "A comprehensive guide to selecting the perfect excavator based on your project requirements.",
    date: "2024-12-10",
    image: "/placeholder.svg",
  },
  {
    id: 3,
    title: "Benefits of Renting vs Buying Heavy Equipment",
    slug: "renting-vs-buying-equipment",
    excerpt: "Explore the advantages of equipment rental for your construction business.",
    date: "2024-12-05",
    image: "/placeholder.svg",
  },
  {
    id: 4,
    title: "Safety Tips for Operating Heavy Machinery",
    slug: "safety-tips-heavy-machinery",
    excerpt: "Essential safety guidelines for operators working with heavy construction equipment.",
    date: "2024-11-28",
    image: "/placeholder.svg",
  },
  {
    id: 5,
    title: "The Future of Construction Equipment Technology",
    slug: "future-construction-equipment-technology",
    excerpt: "How technology is transforming the heavy equipment industry in the UAE and beyond.",
    date: "2024-11-20",
    image: "/placeholder.svg",
  },
  {
    id: 6,
    title: "Maintenance Tips to Extend Equipment Lifespan",
    slug: "maintenance-tips-equipment-lifespan",
    excerpt: "Professional maintenance practices to maximize the life of your rental equipment.",
    date: "2024-11-15",
    image: "/placeholder.svg",
  },
];
